<?php

namespace Nassirian\GitHubDeployer\Tests;

use Nassirian\GitHubDeployer\Deployers\SyncDeployer;
use Illuminate\Support\Facades\Config;

class SyncDeployerTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Config::set('github-deployer.mode', 'sync');
    }

    /** @test */
    public function test_it_runs_all_commands_successfully_in_sync_mode()
    {

        Config::set('github-deployer.pre_deploy_commands', ['echo "Pre Deploy successful"']);
        Config::set('github-deployer.deploy_commands', ['echo "Deploy successful"']);
        Config::set('github-deployer.post_deploy_commands', ['echo "Post Deploy successful"']);

        $deployer = app(SyncDeployer::class);

        $output = $deployer->deploy();

        $this->assertEquals('completed', $output['status']);
        $this->assertStringContainsString('Deploy successful', $output['deploy']['echo "Deploy successful"']);
    }

    /** @test */
    public function test_it_throws_exception_if_command_fails_in_sync_mode()
    {
        Config::set('github-deployer.deploy_commands', ['non_existing_command_should_fail']);

        $deployer = app(SyncDeployer::class);

        $this->expectException(\RuntimeException::class);
        $deployer->deploy();
    }
}
